name: Build Project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MALI_LIBS: /usr/lib
      MALI_INCLUDE: /usr/include
      ARM_CROSS_COMPILER_PATH: /usr/bin/aarch64-linux-gnu-g++
      ARM_CROSS_COMPILER_PATH_C: /usr/bin/aarch64-linux-gnu-gcc
      CXXFLAGS: -DENABLE_X11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 
      # 新增步驟：安裝 ARM 跨編譯器
      #
      - name: Install ARM Cross-Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Run make
        run: make